### ISSUE TITLE
Add original support for CTRL-key as in caprice3.5.3 - caprice3.6.4

### ISSUE THREAD

**Issue by zackizacki** [ColinPitrat/caprice32#151]
I have not yet figured out what other side effect this missing feature has. but here the obvious:

on the original CPC you could enter CTRL-Codes via CTRL-A to CTRL-Z. 

For example you could easily switch to inverse video mode when you typed in this key combination:

print "<CTRL-X>

This was also supported on the classic caprice32 window versions up to 3.6.4
With the remake this feature was lost and nothing happens, when CTRL-A etc is pressed.

Would be nice to figure at least out how this could be implemented.

**Comment by ColinPitrat** [comment]
Indeed, this is something that is caused by the way the keyboard is handled in caprice.
Instead of mapping a physical key from the computer to a physical key of the CPC, we map a key combination to another key combination.
The reason for that is that it's preferable to have special characters on the key where they are on the computer's keyboard rather than having to know the layout of the CPC keyboard to know which key to press to get the character you want.

The drawback is that any combination that is not explicitly mapped (like CTRL-X for example) is not available.

I'll have a look into the control keys.

**Comment by zackizacki** [comment]
Ah, I see. Thats fine. So it is good to clear up, if it can be done and is a real option.

Maybe we should ask the community, if any popular application relies on the control key combinations? I'm thinking of CP/M, Tasword, Context and these non gaming stuff.

Interesting for me, that here is also kind of cultural difference. 
When I was windows user and was frequently using caprice and / or winape 
there was no other way than to remember the original uk keyboard 
layout of the schneider cpc. 

So when I did some experiments on the emulator, like basic hacks or maxam assembler routines I used to load a special cpc basic program to be able to use the german PC keyboard with a one to one mapping:

100 'german key definitions
110 '
120 'use your german pc keyboard to 
130 'type in programs as usually on
140 'the caprice32 cpc emulator
150 '--------------------------------
160 KEY DEF 43, 1, ASC("z"), ASC("Z")
170 KEY DEF 71, 1, ASC("y"), ASC("Y")
180 KEY DEF 19, 1, ASC("#"), ASC("'")
190 KEY DEF 17, 1, ASC("+"), ASC("*")
200 KEY DEF 29, 1, ASC("["), ASC("{")
210 KEY DEF 28, 1, ASC("]"), ASC("}")        
220 KEY DEF 39, 1, ASC(","), ASC(";"), ASC("<")  
230 KEY DEF 31, 1, ASC("."), ASC(":"), ASC(">")   
240 KEY DEF 57, 1, ASC("3"), ASC("§")
250 KEY DEF 41, 1, ASC("7"), ASC("/"), ASC("{")
260 KEY DEF 30, 1, ASC("-"), ASC("_")
270 KEY DEF 40, 1, ASC("8"), ASC("("), ASC("[")
280 KEY DEF 33, 1, ASC("9"), ASC(")"), ASC("]")     
290 KEY DEF 32, 1, ASC("0"), ASC("="), ASC("}")
300 KEY DEF 25, 1, ASC("\"), ASC("?")
310 ' give the enter key a repeat
320 KEY DEF 18,1

which worked out very good and it did not mess with the keyboard layout so all games worked as usal. 
But I don't know how to map the keys in CP/M, and I don't need to as I am also 
familiar with the original cpc keyboard.

So, the two keyboard files I provided for the german pc keyboard are the exact the same as caprice 3.6.4 or winape. They also map to the original cpc layout and do no one to one translation. Thus the winape users and classic caprice users with german pc keyboard will find the same they are used to in caprice 4.5.0.

**Comment by ColinPitrat** [comment]
Interesting. Not having to use this kind of tricks is a feature that I like in Caprice :-)

One option could be to have multiple mappings for a same language: "physical" and "logical" (better names are welcome) to match both preferences.

I'd definitely like to support the control keys. I'll look into what it requires.

**Comment by ColinPitrat** [comment]
I implemented _something_ for keys from CTRL-A to CTRL-Z.
It may make sense to support more than just those though, as I think some software were using at least CTRL-0 to CTRL-9.

**Comment by zackizacki** [comment]
Thank you for the release 4.6.0. :-) It is a big step ahead!

I did some testing with the CRTL key support and now caprice32 can also deal with many options
for example in the text processing programs.

Some little issues are still remaining:
On german keymaps CTRL-y and CTRL-x must be exchanged to be correct.

The text programs make heavy use of CTRL-Enter as this is the only way to open the main menus. 
Also CTR / SHIFT is much in use for special cursor movement.

So here is a list of keycodes that are still missing to be very close to the original again.

CTRL-<ENTER>
CTRL-<SPACE>
CTRL-<CURSOR-KEYS>
CTRL-<TAB>
CTRL-<DEL>
CTRL-<CLR>
CTRL-<0-9>
CTRL- ]
CTRL- [
CTRL- <
CTRL- >
CTRL- /
CTRL- \
CTRL- *
CTRL- +
CTRL- -
CTRL-<POWER>
CTRL-<COPY>
CTRL- ,
CTRL- .
CTRL- @
CTRL-<ESC>

SHIFT-<ENTER>
SHIFT-<SPACE>
SHIFT-<CURSOR-KEYS>
SHIFT-<TAB>
SHIFT-<COPY>
SHIFT-<DEL>
SHIFT-<CLR>
SHIFT-<COPY>
SHIFT-<ESC>

BTW: I noticed that both programs, classic caprice and winape seem not to support the backslash key on german keyboards at all. However all other key combinations work there.

**Comment by simulant-systems** [comment]
Hey guys, I'm experiencing the same trouble when I try to use PowerPage 128 on Caprice32 (v4.6.0 from Linux Snap)

There is a menu at the bottom of the DTP program's screen, and to use it on my real CPC I would normally hold Control and then use the arrow keys. However, on Caprice32 this doesn't navigate the menus and nothing happens.

Thanks for any support or a fix.

Keep up the great work.
